apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  labels:
    name: simple-app-service
spec:
  selector:
    name: simple-app
  type: LoadBalancer
  ports:
    - port: 7000
      targetPort: 5000
      # nodePort: 30002
